//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_unit5
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasulityProfile
    {
        public int Id { get; set; }
        public string AddedValue { get; set; }
        public string Assistants { get; set; }
        public string ChildState { get; set; }
        public string Complications { get; set; }
        public Nullable<int> Days { get; set; }
        public string Dynamics { get; set; }
        public string Intervention { get; set; }
        public string Outcome { get; set; }
        public string ParityValue { get; set; }
        public string Presentation { get; set; }
        public Nullable<System.DateTime> rec_date { get; set; }
        public string Sex { get; set; }
        public string State { get; set; }
        public string Supervisors { get; set; }
        public string Surgeons { get; set; }
        public Nullable<int> Weeks { get; set; }
        public Nullable<double> Weight { get; set; }
        public string ICU { get; set; }
        public string patientAge { get; set; }
        public string patientName { get; set; }
        public string ticketId { get; set; }
        public int NumberOfLivingFemale { get; set; }
        public int NumberOfLivingMale { get; set; }
        public string AdmissionDate { get; set; }
        public string InterventionDate { get; set; }
        public string By { get; set; }
        public string Obstetric { get; set; }
        public string Disorder { get; set; }
        public string AdditionalComplications { get; set; }
        public string NeonatalCondition { get; set; }
        public string OtherIntervention { get; set; }
        public string Indications { get; set; }
        public string AdditionalNotes { get; set; }
    }
}
