//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_unit5
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_diagnose
    {
        public int recid { get; set; }
        public string Assistant { get; set; }
        public string child_Presentation { get; set; }
        public string child_state { get; set; }
        public string Complications { get; set; }
        public string cs_indication { get; set; }
        public string Dynamics { get; set; }
        public string GA { get; set; }
        public string Intervention { get; set; }
        public string Outcome { get; set; }
        public string Outcome_sex { get; set; }
        public string Outcome_State { get; set; }
        public Nullable<double> Outcome_weight { get; set; }
        public Nullable<System.DateTime> Positive_date { get; set; }
        public Nullable<System.DateTime> rec_date { get; set; }
        public string Supervisor { get; set; }
        public string Surgeon { get; set; }
    }
}
