//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_unit5.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinical_Rounds
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Insertion_date { get; set; }
        public Nullable<System.DateTime> Lecture_date { get; set; }
        public string Time { get; set; }
        public string group { get; set; }
        public Nullable<int> Lecturer_id { get; set; }
        public Nullable<int> First_Subsitute_id { get; set; }
        public Nullable<int> Second_Subsitute_id { get; set; }
        public string Students_Flag { get; set; }
        public string Attended_flag { get; set; }
    
        public virtual doctor_profile doctor_profile { get; set; }
        public virtual doctor_profile doctor_profile1 { get; set; }
        public virtual doctor_profile doctor_profile2 { get; set; }
    }
}
