//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_unit5.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinical_Rounds
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> rec_date { get; set; }
<<<<<<< HEAD
        public Nullable<System.DateTime> Lecture_date { get; set; }
=======
        public string Lecture_date { get; set; }
>>>>>>> 08a1f10f0695307f636c34b81130c37b3bbf30d9
        public string Time { get; set; }
        public string group { get; set; }
        public string Lecturer_name { get; set; }
        public string First_Subsitute_name { get; set; }
        public string Second_Subsitute_name { get; set; }
        public string Attended_flag { get; set; }
        public string Student_flag { get; set; }
    }
}
