//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_unit5.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_medicalDisorder
    {
        public int Id { get; set; }
        public string element_name { get; set; }
    }
}
