//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_unit5.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor_profile
    {
        public int recid { get; set; }
        public Nullable<System.DateTime> doctor_bach_year { get; set; }
        public Nullable<System.DateTime> doctor_birthdate { get; set; }
        public string doctor_degree { get; set; }
        public string doctor_image_URL { get; set; }
        public Nullable<System.DateTime> doctor_MCS_year { get; set; }
        public string doctor_name { get; set; }
        public string doctor_other_degrees { get; set; }
        public string doctor_other_qualifications { get; set; }
        public Nullable<System.DateTime> doctor_PHD_year { get; set; }
        public string doctor_precense { get; set; }
        public string doctor_title { get; set; }
        public Nullable<System.DateTime> record_date { get; set; }
        public string DoctorLocation { get; set; }
        public string DoctorMail { get; set; }
        public string DoctorMobile { get; set; }
        public string DoctorAcademicDegree { get; set; }
    }
}
