//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_unit5.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gynacology
    {
        public int Id { get; set; }
        public string AddedValue { get; set; }
        public string AdmissionDate { get; set; }
        public string Assistants { get; set; }
        public string ChildState { get; set; }
        public string Complications { get; set; }
        public int Days { get; set; }
        public string DischargeDiagnoses { get; set; }
        public string DischargeFollowupPlan { get; set; }
        public string DischargeSummary { get; set; }
        public string Dynamics { get; set; }
        public string ICU { get; set; }
        public string Intervention { get; set; }
        public int NumberOfLivingFemale { get; set; }
        public int NumberOfLivingMale { get; set; }
        public string OperativeDate { get; set; }
        public string Outcome { get; set; }
        public string ParityValue { get; set; }
        public string Presentation { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public string Sex { get; set; }
        public string State { get; set; }
        public string Supervisors { get; set; }
        public string Surgeons { get; set; }
        public int Weeks { get; set; }
        public double Weight { get; set; }
        public string patientAge { get; set; }
        public string patientName { get; set; }
        public string ticketId { get; set; }
    }
}
