//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_unit5.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecture
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Insertion_Date { get; set; }
        public Nullable<int> Lectrurer_ID { get; set; }
        public Nullable<int> Subsitute_Id { get; set; }
        public string Topic { get; set; }
        public Nullable<System.DateTime> Lecture_Date { get; set; }
        public string Attended_flag { get; set; }
        public string Students_Flag { get; set; }
    
        public virtual doctor_profile doctor_profile { get; set; }
        public virtual doctor_profile doctor_profile1 { get; set; }
    }
}
