//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_unit5.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_profile
    {
        public int recid { get; set; }
        public string patient_address { get; set; }
        public Nullable<double> patient_age { get; set; }
        public Nullable<System.DateTime> patient_birthdate { get; set; }
        public string patient_contact { get; set; }
        public string patient_email { get; set; }
        public string patient_id { get; set; }
        public string patient_image_url { get; set; }
        public string Patient_name { get; set; }
        public string patient_sex { get; set; }
        public Nullable<System.DateTime> rec_date { get; set; }
    }
}
