//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_unit5.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Research
    {
        public int Id { get; set; }
        public Nullable<int> Supervisor_1 { get; set; }
        public int Supervisor_2 { get; set; }
        public int Researcher_id { get; set; }
        public string Reasearch_Name { get; set; }
    
        public virtual doctor_profile doctor_profile { get; set; }
        public virtual doctor_profile doctor_profile1 { get; set; }
        public virtual doctor_profile doctor_profile2 { get; set; }
    }
}
