//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_unit5.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Research
    {
        public int Id { get; set; }
        public string Super1 { get; set; }
        public string Super2 { get; set; }
        public string Super3 { get; set; }
        public string Super4 { get; set; }
        public string Super5 { get; set; }
        public string Researcher_Staff { get; set; }
        public string Researcher_External { get; set; }
        public string Research_Title { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> Registration_date { get; set; }
        public Nullable<System.DateTime> Rec_id { get; set; }
    }
}
