//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_unit5.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class unit5Entities : DbContext
    {
        public unit5Entities()
            : base("name=unit5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<CasulityProfile> CasulityProfiles { get; set; }
        public virtual DbSet<Complicaiton> Complicaitons { get; set; }
        public virtual DbSet<conf_by> conf_by { get; set; }
        public virtual DbSet<conf_child_presentation> conf_child_presentation { get; set; }
        public virtual DbSet<conf_child_state> conf_child_state { get; set; }
        public virtual DbSet<conf_cs_indication> conf_cs_indication { get; set; }
        public virtual DbSet<conf_degree> conf_degree { get; set; }
        public virtual DbSet<conf_GynaDisorder> conf_GynaDisorder { get; set; }
        public virtual DbSet<conf_Intervention> conf_Intervention { get; set; }
        public virtual DbSet<conf_medicalDisorder> conf_medicalDisorder { get; set; }
        public virtual DbSet<conf_medicalObestetric> conf_medicalObestetric { get; set; }
        public virtual DbSet<conf_Outcome> conf_Outcome { get; set; }
        public virtual DbSet<conf_Outcome_State> conf_Outcome_State { get; set; }
        public virtual DbSet<conf_title> conf_title { get; set; }
        public virtual DbSet<doctor_profile> doctor_profile { get; set; }
        public virtual DbSet<Gynacology> Gynacologies { get; set; }
        public virtual DbSet<NeonatalOutcome> NeonatalOutcomes { get; set; }
        public virtual DbSet<patient_diagnose> patient_diagnose { get; set; }
        public virtual DbSet<patient_profile> patient_profile { get; set; }
        public virtual DbSet<Clinical_Rounds> Clinical_Rounds { get; set; }
        public virtual DbSet<Lecture> Lectures { get; set; }
        public virtual DbSet<Research> Researches { get; set; }
    }
}
